Simplify

diff --git a/rofi-pass b/rofi-pass
--- a/rofi-pass
+++ b/rofi-pass
@@ -87,82 +87,78 @@ generateOTP () {
    fi
 }
 
-mainMenu () {
-   unset selected_password
-
-   args=( -dmenu
-      -kb-custom-1 "${autotype}"
-      -kb-custom-2 "${type_user}"
-      -kb-custom-3 "${type_pass}"
-      -p ">"
-   )
-
-   selected_password="$(list_passwords 2>/dev/null | _rofi "${args[@]}")"
-
-   rofi_exit=$?
-   if [[ $rofi_exit -eq 1 ]]; then
-      exit
-   fi
-
-   mapfile -t password_temp < <(PASSWORD_STORE_DIR="${root}" pass show "$selected_password")
-   password=${password_temp[0]}
-
-   fields=$(printf '%s\n' "${password_temp[@]:1}" | awk '$1 ~ /:$/ || /otpauth:\/\// {$1=$1;print}')
-   declare -A stuff
-   stuff["pass"]=${password}
-
-   if [[ -n $fields ]]; then
-      while read -r LINE; do
-         unset _id _val
-         case "$LINE" in
-            "otpauth://"*|"${OTPmethod_field}"*)
-               _id="OTP"
-               _val=""
-               ;;
-            *)
-               _id="${LINE%%: *}"
-               _val="${LINE#* }"
-               ;;
-         esac
-
-         if [[ -n "$_id" ]]; then
-            stuff["${_id}"]=${_val}
-         fi
-      done < <(printf '%s\n' "${fields}")
-
-      if test "${stuff['autotype']+autotype}"; then
-         :
-      else
-         stuff["autotype"]="${USERNAME_field} :tab pass"
-      fi
-   fi
-
-   if [[ -z "${stuff["${AUTOTYPE_field}"]}" ]]; then
-      if [[ -n $default_autotype ]]; then
-         stuff["${AUTOTYPE_field}"]="${default_autotype}"
-      fi
-   fi
-   if [[ -z "${stuff["${USERNAME_field}"]}" ]]; then
-      if [[ -n $default_user ]]; then
-         if [[ "$default_user" == ":filename" ]]; then
-            stuff["${USERNAME_field}"]="$(basename "$selected_password")"
-         else
-            stuff["${USERNAME_field}"]="${default_user}"
-         fi
-      fi
-   fi
-
-   # actions based on keypresses
-   # The exit code for -kb-custom-X is X+9.
-   case "${rofi_exit}" in
-      0) sleep $wait; autopass;;
-      10) sleep $wait; autopass;;
-      11) sleep $wait; typeUser;;
-      12) sleep $wait; typePass;;
-   esac
-}
 
 
 root="$HOME/.password-store"
 export PASSWORD_STORE_DIR="${root}"
-mainMenu
+
+args=( -dmenu
+   -kb-custom-1 "${autotype}"
+   -kb-custom-2 "${type_user}"
+   -kb-custom-3 "${type_pass}"
+   -p ">"
+)
+
+selected_password="$(list_passwords 2>/dev/null | _rofi "${args[@]}")"
+
+rofi_exit=$?
+if [[ $rofi_exit -eq 1 ]]; then
+   exit
+fi
+
+mapfile -t password_temp < <(PASSWORD_STORE_DIR="${root}" pass show "$selected_password")
+password=${password_temp[0]}
+
+fields=$(printf '%s\n' "${password_temp[@]:1}" | awk '$1 ~ /:$/ || /otpauth:\/\// {$1=$1;print}')
+declare -A stuff
+stuff["pass"]=${password}
+
+if [[ -n $fields ]]; then
+   while read -r LINE; do
+      unset _id _val
+      case "$LINE" in
+         "otpauth://"*|"${OTPmethod_field}"*)
+            _id="OTP"
+            _val=""
+            ;;
+         *)
+            _id="${LINE%%: *}"
+            _val="${LINE#* }"
+            ;;
+      esac
+
+      if [[ -n "$_id" ]]; then
+         stuff["${_id}"]=${_val}
+      fi
+   done < <(printf '%s\n' "${fields}")
+
+   if test "${stuff['autotype']+autotype}"; then
+      :
+   else
+      stuff["autotype"]="${USERNAME_field} :tab pass"
+   fi
+fi
+
+if [[ -z "${stuff["${AUTOTYPE_field}"]}" ]]; then
+   if [[ -n $default_autotype ]]; then
+      stuff["${AUTOTYPE_field}"]="${default_autotype}"
+   fi
+fi
+if [[ -z "${stuff["${USERNAME_field}"]}" ]]; then
+   if [[ -n $default_user ]]; then
+      if [[ "$default_user" == ":filename" ]]; then
+         stuff["${USERNAME_field}"]="$(basename "$selected_password")"
+      else
+         stuff["${USERNAME_field}"]="${default_user}"
+      fi
+   fi
+fi
+
+# actions based on keypresses
+# The exit code for -kb-custom-X is X+9.
+case "${rofi_exit}" in
+   0) sleep $wait; autopass;;
+   10) sleep $wait; autopass;;
+   11) sleep $wait; typeUser;;
+   12) sleep $wait; typePass;;
+esac
